### PR TITLE
feat: init the driver app

### PR DESCRIPTION
**Pull request by TennyZhuang**
Signed-off-by: TennyZhuang <zty0826@gmail.com>

### CODE REVIEW

**Comment by TennyZhuang** [comment]
Will add README and ci checker later

**Review by xxchan — APPROVED** [review]
LGTM

**Comment by wangrunji0408** [comment]
A silly question: why don't we put it together with sqllogictest-rs? 🥵

**Review by wangrunji0408 — APPROVED** [review]
LGTM!

**Comment by TennyZhuang** [comment]
> A silly question: why don't we put it together with sqllogictest-rs? 🥵

Not sure it's a good practice to create a cross-lang project

**Comment by TennyZhuang** [comment]
But it's also acceptable to me

**Pull request merged**
